version: '3'

services:
  pokedex:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: pokedex
    container_name: pokedex-server
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
  db:
    image: mongo:5
    container_name: pokedex-db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db
